---
- name: "[{{ name }}]: Конфигурация секрета"
  include: "../secret-config.yml"

- name: "[{{ name }}]: Выкладка сервиса"
  block:
  - name: "[{{ name }}]: Выкладка сервиса"
    community.docker.docker_swarm_service:
      name: "{{ name }}"
      image: "{{ registry_name }}{{ name }}:{{ version }}"
      state: present
      force_update: true
      networks:
        - name: "{{ network_name }}"
      publish:
        - mode: ingress
          protocol: tcp
          published_port: 3100
          target_port: 3100
      secrets:
        - secret_name: "{{ name }}"
          filename: "/opt/app/envs/.{{ name }}.env"
  tags: "{{ name }}"
