CREATE SCHEMA IF NOT EXISTS `account`;
CREATE SCHEMA IF NOT EXISTS `reference`;
CREATE SCHEMA IF NOT EXISTS `document_detail`;
CREATE SCHEMA IF NOT EXISTS `correction`;
CREATE SCHEMA IF NOT EXISTS `single_payment_document`;
CREATE SCHEMA IF NOT EXISTS `payment`;
CREATE SCHEMA IF NOT EXISTS `event`;
