---
- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: Создание папки
      file:
        path: /home/vagrant/mongo
        state: directory
        mode: '0755'
    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{ name }}:{{ version }}"
        state: present
        networks:
          - name: "{{ network_name }}"
        env:
          - MONGO_INITDB_ROOT_USERNAME={{ mongo.user }}
          - MONGO_INITDB_ROOT_PASSWORD={{ mongo.password }}
        mounts:
          - type: bind
            source: /home/vagrant/mongo
            target: /var/lib/dbdata/mongo
        placement:
          constraints:
            - "node.hostname == {{ host_name }}"
  tags: "{{ name }}"