- name: "[{{ name }}]: Создание секрета"
  vars:
    env_file: "{{ lookup('template', '{{ name }}/.env.j2') }}"
    secret_name: "{{ name | regex_replace('[^a-zA-Z0-9]', '_') }}"
  community.docker.docker_secret:
    name: "{{ secret_name }}"
    data: "{{ env_file | b64encode }}"
    labels:
      secret: "{{ env_file | hash('sha1') }}"
    data_is_b64: true
    state: present